### ISSUE TITLE
node server throws error

### ISSUE THREAD

**Issue by franktopel** [gustaYo/vue-chess#4]
I have done the following:

1. `git clone git@github.com:gustaYo/vue-chess.git`
2. `cd vue-chess`
3. `npm install`
4. `yes | cp -rf -- copy_in_node_modules/ node_modules/`
5. `node server`

```
> node server
module.js:540
    throw err;
    ^

Error: Cannot find module 'compression'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at __dirname (/Users/connexo/Sites/vue-chess/server/app/index.js:11:16)
    at Object.<anonymous> (/Users/connexo/Sites/vue-chess/server/app/index.js:95:3)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
```

**Comment by gil2gm** [comment]
cd server
npm install

**Comment by cgencer** [comment]
npm run build after the above gives these errors:

ERROR in ./~/vue-material-components/dist/vue-material-components.js
Module not found: Error: Cannot resolve module 'Vue' in /home/vc/node_modules/vue-material-components/dist
 @ ./~/vue-material-components/dist/vue-material-components.js 3:27-41

ERROR in ./~/babel-loader/lib?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/vue-loader/lib/selector.js?type=script&index=0!./~/eslint-loader!./src/components/game/index.vue
Module not found: Error: Cannot resolve module 'garbochess' in /home/vc/src/components/game
 @ ./~/babel-loader/lib?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/vue-loader/lib/selector.js?type=script&index=0!./~/eslint-loader!./src/components/game/index.vue 19:18-39

ERROR in ./~/babel-loader/lib?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/vue-loader/lib/selector.js?type=script&index=0!./~/eslint-loader!./src/components/home/boardVisor.vue
Module not found: Error: Cannot resolve module 'garbochess' in /home/vc/src/components/home
 @ ./~/babel-loader/lib?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/vue-loader/lib/selector.js?type=script&index=0!./~/eslint-loader!./src/components/home/boardVisor.vue 15:18-39

ERROR in ./~/babel-loader/lib?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/vue-loader/lib/selector.js?type=script&index=0!./~/eslint-loader!./src/components/puzzles/puzzle.vue
Module not found: Error: Cannot resolve module 'garbochess' in /home/vc/src/components/puzzles
 @ ./~/babel-loader/lib?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/vue-loader/lib/selector.js?type=script&index=0!./~/eslint-loader!./src/components/puzzles/puzzle.vue 15:18-39
